"""empty message

Revision ID: 9adee034c9ea
Revises: 
Create Date: 2023-04-10 10:49:37.919814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9adee034c9ea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('title', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('poster', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('poster')
        batch_op.drop_column('description')
        batch_op.drop_column('title')
        batch_op.drop_column('id')

    # ### end Alembic commands ###
